### ISSUE TITLE
Use StreamURLFetcher & PyTube instead of youtube_dl

### ISSUE THREAD

**Issue by alexmercerind** [Darkempire78/Music-Discord-Bot#2]
Hi there!

I recently saw this project from you.
I'm maintainer of [youtube-search-python](https://github.com/alexmercerind/youtube-search-python) & I made few additions to my project which you might like.

As you might be aware, that youtube_dl or vanilla PyTube is kinda slow to get video URLs as they make "additional web requests" for getting the exact same response which you already have when displaying it to the user.

```py
from youtubesearchpython import *
fetcher = StreamURLFetcher() # Instantiate this class only once (makes web requests).

video = Video.get("https://www.youtube.com/watch?v=aqz-KE-bpKQ") # Let's assume you get information of this video for displaying.
url = fetcher.get(video, 251) # You can use same response to get its stream URL (Very fast, does not make any requests).
print(url)
```

See more [here](https://github.com/alexmercerind/youtube-search-python#getting-direct-stream-url-of-a-video).

Thankyou, I just wanted to let you know.

NOTE: I'm not sure how stable it is at the moment, but is definitely worth trying.
You may close (or delete) this issue, once you read.

**Comment by Darkempire78** [comment]
I will check this.
Thanks!

**Comment by Darkempire78** [comment]
@alexmercerind It's perhaps stupid, but i do not really find how get the video lengh 🤔

**Comment by alexmercerind** [comment]
@Darkempire78 it is present in "streamingData" of the Video.get.

**Comment by Darkempire78** [comment]
It does not work with YouTube live contrary to Youtube_dl, so i need to check if the link is a live when stream_url is None i think

**Comment by Darkempire78** [comment]
changed!
