### ISSUE TITLE
Missing from requirements.txt + playlist limits

### ISSUE THREAD

**Issue by ebarcsa** [Darkempire78/Music-Discord-Bot#6]
Hi
After some time managed to run it, well there are some glitches with music,
i don't know if it's because Lavalink, but i see its resource usage is minimal yet
periodically stutters, what's worse is sometimes then speeds up to match timestamp,
occasionally quality drops, so many problems, maybe its Discord? I'm new to all this.
I think these are missing from requirements.txt
wavelink
youtube-search-python
psutil
Also the 15 limit for playlist is absurd, queues too, either remove or raise.
Also the shuffle isn't working as advertised :) but i see you have task for that.
Thanks

**Comment by Darkempire78** [comment]
Thanks for the requirements.txt
> Also the 15 limit for playlist is absurd, queues too, either remove or raise.
It's to prevent from bot lag, but if there are not a lot of users, you can remove them
